          <p><span class="special">First Choice Committee: </span> <?php echo(htmlspecialchars($committee_1));?></p>
          <p><span class="special">Second Choice Committee: </span> <?php echo(htmlspecialchars($committee_2));?></p>
          <p><span class="special">Third Choice Committee: </span> <?php echo(htmlspecialchars($committee_3));?></p> 
          <p><span class="special">Fourth Choice Committee: </span> <?php echo(htmlspecialchars($committee_4));?></p>
          <p><span class="special">Fifth Choice Committee: </span> <?php echo(htmlspecialchars($committee_5));?></p>
          <p class="special">1. What attracts your delegation to the Specialized Agencies?</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_1));?></p>
          <p class="special">2. What experience or interest does your delegation have in small or crisis-based committees?</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_2));?></p>
          <p class="special">3. Does your delegation have any special knowledge or expertise in any of the top three committees ranked?</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_3));?></p>
          <p class="special">4. TPA only: What experience or interest does your delegation have in representing organizations such as press and NGOs at Model UN conferences? </p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_4));?></p>
          <p class="special">5. If the Cabinet of Gamal Abdel Nasser is selected above, please rank at least five and no more than eight characters below:</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_5));?></p>
          <p class="special">6. If the Committee of Public Safety is selected above, please rank at least five and no more than eight characters below:</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_6));?></p>
          <p class="special">7. If INTERPOL is selected above, please rank at least five and no more than eight characters below:</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_7));?></p>
          <p class="special">8. If Pandemic Response Team is selected above, please rank at least five and no more than eight characters below:</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_8));?></p>
          <p class="special">9. If Third Party Actors is selected above, please indicate press, NGO, or no preference and rank 3-5 assignments.</p> 
          <p class="answer"><?php echo(htmlspecialchars($sa_9));?></p>